### ISSUE TITLE
Include example with autopublish removed

### ISSUE THREAD

**Issue by steve-ross** [meteor-useraccounts/boilerplates#11]
These examples are great, however don't really match real world scenarios where you would remove autopublish.

**Comment by splendido** [comment]
IMHO these could be the starting point for bigger projects, and every project starts with `autopublish` included.
...usually after a bit of prototyping work, when you get to the point about security and subscriptions, you remove `autopublish` and a new design phase starts.

So I think it's fine to have `autopublish` included since these are *boilerplates* and not complete projects.
