### ISSUE TITLE
materialize-flow-router Sign in button no longer responds

### ISSUE THREAD

**Issue by dandv** [meteor-useraccounts/boilerplates#13]
To reproduce, launch the boilerplate, navigate to /, click on `private`, then go back in the browser, then click "Sign in".

**Comment by 100ideas** [comment]
Just encountered this as well.

**Comment by jshimko** [comment]
Good catch!  This bug was because of the `AccountsTemplates.avoidRedirect` state that was left over from the Iron Router implementation of `ensureSignedIn`.  When you hit `/private` the first time, it [set `avoidRedirect` to true][1] which then broke the redirect that we needed for the Flow Router implementation of `ensureSignedIn`.  [This commit][2] fixes the issue.  It should be all set once the `useraccounts:flow-routing` package gets published again.

Sorry for any inconvenience.  Thanks for reporting it guys!  

[1]: https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L63
[2]: https://github.com/meteor-useraccounts/flow-routing/commit/5f482eb377fcbce719002ed283c12bd75fe60fa0

**Comment by dandv** [comment]
Thanks @jshimko for the quick fix!
